# Supervised Learning - Building a Student Performace Prediction System


# Classification vs. Regression
The aim of this project is to predict how likely a student is to pass. Which type of supervised learning problem is this, classification or regression? Why?
Answer:
This project is a classification supervised learning problem because the variable to predict, i.e. if a student graduates or fails to graduate, is categorical. On this case this a dichotomous categorical variable where the only two possible values are "pass" or "fail".

### Overview:

1.Read the problem statement.

2.Get the dataset.

3.Explore the dataset.

4.Pre-processing of dataset.

5.Transform the dataset for building machine learning model.

6.Split data into train, test set.

7.Build Model.

8.Apply the model.

9.Evaluate the model.

10.Provide insights.

## Problem Statement 

Using Logistic Regression **predict the performance of student**. The classification goal is to predict whether the student will pass or fail.

## Dataset 

This data approach student achievement in secondary education of two Portuguese schools. The data attributes include student grades, demographic, social and school related features) and it was collected by using school reports and questionnaires. Two datasets are provided regarding the performance in Mathematics.

**Source:** https://archive.ics.uci.edu/ml/datasets/Student+Performance

# Question 1 - Exploring the Data (0.5 points)
*Read the dataset file using pandas. Take care about the delimiter.*

#### Answer:

In [14]:
import warnings
warnings.filterwarnings('ignore')


# Numerical libraries
import numpy as np   

# Import Linear Regression machine learning library
from sklearn.linear_model import LinearRegression

# to handle data in form of rows and columns 
import pandas as pd    

# importing ploting libraries
import matplotlib.pyplot as plt   
import matplotlib.style
#plt.style.use('classic')

#importing seaborn for statistical plots
import seaborn as sns

from sklearn.model_selection import train_test_split

In [15]:
"""
* The following assumes 'Jupyter Notebook' command is run where the dataset 'students.csv' resides
* Configure os path accordingly if your current working directory is different
"""

students_df = pd.read_csv('students-data.csv', delimiter = ';')
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

# Question 2 - drop missing values (0.5 points)
*Set the index name of the dataframe to **"number"**. Check sample of data to drop if any missing values are there.*
*Use .dropna() function to drop the NAs*

#### Answer:

In [16]:
students_df.index.name = 'number'
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
number                                                                          
0          GP   F   18       U     GT3       A     4     4  at_home   teacher   
1          GP   F   17       U     GT3       T     1     1  at_home     other   
2          GP   F   15       U     LE3       T     1     1  at_home     other   
3          GP   F   15       U     GT3       T     4     2   health  services   
4          GP   F   16       U     GT3       T     3     3    other     other   

       ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
number ...                                                                 
0      ...      4        3      4     1     1      3        6   5   6   6  
1      ...      5        3      3     1     1      3        4   5   5   6  
2      ...      4        3      2     2     3      3       10   7   8  10  
3      ...      3        2      2     1     1      5        2  15  14  15  
4      ...      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [17]:
students_df[students_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

[0 rows x 33 columns]

# Transform Data

## Question 3 (0.5 points)

*Print all the attribute names which are not numerical.*

**Hint:** check **select_dtypes()** and its **include** and **exclude** parameters.**

#### Answer:

In [18]:
df = students_df.select_dtypes(exclude = ['int64'])
df.dtypes

school        object
sex           object
address       object
famsize       object
Pstatus       object
Mjob          object
Fjob          object
reason        object
guardian      object
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
dtype: object

In [20]:
df2 = students_df.select_dtypes(include = 'int64')
df2.dtypes

age           int64
Medu          int64
Fedu          int64
traveltime    int64
studytime     int64
failures      int64
famrel        int64
freetime      int64
goout         int64
Dalc          int64
Walc          int64
health        int64
absences      int64
G1            int64
G2            int64
G3            int64
dtype: object

# Question 4 - Drop variables with less variance (0.5 points)

*Find the variance of each numerical independent variable and drop whose variance is less than 1. Use .var function to check the variance*

In [21]:
df2_dep = df2[['G1','G2','G3']]
df2_ind = df2.drop(['G1','G2','G3'], axis=1)
df2_ind.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
number                                                                       
0        18     4     4           2          2         0       4         3   
1        17     1     1           1          2         0       5         3   
2        15     1     1           1          2         3       4         3   
3        15     4     2           1          3         0       3         2   
4        16     3     3           1          2         0       4         3   

        goout  Dalc  Walc  health  absences  
number                                       
0           4     1     1       3         6  
1           3     1     1       3         4  
2           2     2     3       3        10  
3           2     1     1       5         2  
4           2     1     2       5         4

In [9]:
bool = df2_ind.var()>=1
df3 = df2_ind.loc[:,bool.values]
df3.head()

age  Medu  Fedu  goout  Walc  health  absences
number                                                
0        18     4     4      4     1       3         6
1        17     1     1      3     1       3         4
2        15     1     1      2     3       3        10
3        15     4     2      2     1       5         2
4        16     3     3      2     2       5         4

#### Variables with less variance are almost same for all the records. Hence, they do not contribute much for classification.

# Question 6 - Encode all categorical variables to numerical (0.5 points)

Take the list of categorical attributes(from the above result) and convert them into neumerical variables. After that, print the head of dataframe and check the values.

**Hint:** check **sklearn LabelEncoder()**

#### Answer:

In [10]:
from sklearn.preprocessing import LabelEncoder

In [22]:
df = df.apply(LabelEncoder().fit_transform)

In [23]:
df.head()

school  sex  address  famsize  Pstatus  Mjob  Fjob  reason  guardian  \
number                                                                         
0            0    0        1        0        0     0     4       0         1   
1            0    0        1        0        1     0     2       0         0   
2            0    0        1        1        1     0     2       2         1   
3            0    0        1        0        1     1     3       1         1   
4            0    0        1        0        1     2     2       1         0   

        schoolsup  famsup  paid  activities  nursery  higher  internet  \
number                                                                   
0               1       0     0           0        1       1         0   
1               0       1     0           0        0       1         1   
2               1       0     1           0        1       1         1   
3               0       1     1           1        1       1         1   
4               0       1     1           0        1       1         0   

        romantic  
number            
0              0  
1              0  
2              0  
3              1  
4              0

# Question 7 - Convert the continuous values of grades into classes (1 point)

*Consider the values in G1, G2 and G3 with >= 10 as pass(1) and < 10 as fail(0) and encode them into binary values. Print head of dataframe to check the values.*

#### Answer:

In [24]:
df2_dep = df2_dep>=10
df2_dep = df2_dep.astype(int)

In [26]:
df2_dep.sample(5)

G1  G2  G3
number            
290      1   1   1
133      1   1   1
292      1   1   1
134      0   0   0
159      1   1   1

In [27]:
students_df1 = pd.concat([pd.DataFrame(df),pd.DataFrame(df3),pd.DataFrame(df2_dep)],axis=1)
students_df1.head()

school  sex  address  famsize  Pstatus  Mjob  Fjob  reason  guardian  \
number                                                                         
0            0    0        1        0        0     0     4       0         1   
1            0    0        1        0        1     0     2       0         0   
2            0    0        1        1        1     0     2       2         1   
3            0    0        1        0        1     1     3       1         1   
4            0    0        1        0        1     2     2       1         0   

        schoolsup ...  age  Medu  Fedu  goout  Walc  health  absences  G1  G2  \
number            ...                                                           
0               1 ...   18     4     4      4     1       3         6   0   0   
1               0 ...   17     1     1      3     1       3         4   0   0   
2               1 ...   15     1     1      2     3       3        10   0   0   
3               0 ...   15     4     2      2     1       5         2   1   1   
4               0 ...   16     3     3      2     2       5         4   0   1   

        G3  
number      
0        0  
1        0  
2        1  
3        1  
4        1  

[5 rows x 27 columns]

# Question 8 (0.5 points)

*Consider G3 is the target attribute and remaining all attributes as features to predict G3. Now, separate feature and target attributes into separate dataframes with X and y variable names.*

In [29]:
y = students_df1['G3']
X = students_df1.drop(['G3'], axis=1)

In [30]:
y.shape

(395,)

In [31]:
X.shape

(395, 26)

# Question 9 - Training and testing data split (0.5 points)

# *So far, you have converted all categorical features into numeric values. Now, split the data into training and test sets with training size of 300 records. Print the number of train and test records.*

**Hint:** check **train_test_split()** from **sklearn**

#### Answer:

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [35]:
X_train.shape

(316, 26)

In [39]:
y_train.shape

(316,)

In [40]:
X_test.shape

(79, 26)

In [38]:
y_test.shape

(79,)

# Question 10 - Model Implementation and Testing the Accuracy (0.5 points)

*Build a **LogisticRegression** classifier using **fit()** functions in sklearn. 
* You need to import both Logistic regression and accuracy score from sklearn*
#### Answer:

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred_tr = model.predict(X_train)
y_predict = model.predict(X_test)
model_score = model.score(X_test, y_test)

In [45]:
print(model_score)

0.8987341772151899


In [43]:
print(metrics.confusion_matrix(y_test, y_predict))

[[20  4]
 [ 4 51]]


In [46]:
print(metrics.classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83        24
           1       0.93      0.93      0.93        55

   micro avg       0.90      0.90      0.90        79
   macro avg       0.88      0.88      0.88        79
weighted avg       0.90      0.90      0.90        79



# Question 11 - Print the intercept of the Logistic regression model (0.5 points)

The value of the intercepts are stored in the model itself. You can use .intercept_ function to do the same

In [49]:
model.intercept_

array([0.55402441])

# Question 12 - Print the coefficients of the model (0.5 points) and name the coefficient which has the highest impact on the dependent variable (0.5 points)

Hint: Use .coef_ to get the coefficients and use pd.Dataframe to store the coefficients in a dataframe with column names same as the independent variable dataframe

In [50]:
model.coef_

array([[ 1.65626756e-01, -1.47472575e-01,  1.63438606e-01,
         1.44066537e-01, -3.66823738e-01, -7.60659131e-02,
         3.00739512e-01,  2.07735439e-01, -9.30543937e-02,
        -2.88805564e-01, -2.95857145e-01,  3.08585967e-01,
        -1.83800831e-01, -8.79820126e-02,  1.20006278e+00,
        -1.45373370e-02, -5.07880717e-01, -1.81560553e-01,
         1.25392240e-01, -4.69865992e-01, -1.98825494e-01,
         4.06865566e-01, -2.50026534e-05, -2.39081025e-02,
         1.44476054e+00,  4.01040787e+00]])

# Question 13 - Predict the dependent variable for both training and test dataset (0.5 points)

Accuracy score() should help you to print the accuracies

In [53]:
print('For Training Sets: ','f1 score: ', metrics.f1_score(y_pred_tr, y_train), 
      'accuracy score: ', metrics.accuracy_score(y_pred_tr, y_train))

For Training Sets:  f1 score:  0.9563106796116505 accuracy score:  0.9430379746835443


In [54]:
print('For Test Sets: ','f1 score: ', metrics.f1_score(y_predict, y_test), 
      'accuracy score: ', metrics.accuracy_score(y_predict, y_test))

For Test Sets:  f1 score:  0.9272727272727272 accuracy score:  0.8987341772151899
